#!/bin/bash
cp $WALLPAPERS/minimalist/minimalist14.jpg $HOME/.config/GIMP/2.10/splashes/
backlight_control 100
#blueman-applet &
compton &
megasync &
nitrogen --restore &
nm-applet &
numlockx
udiskie -t &




