#! /bin/sh

#
#                 ░█▀▄░█▀▀░█▀█░█░█░█▄█
#                 ░█▀▄░▀▀█░█▀▀░█▄█░█░█
#                 ░▀▀░░▀▀▀░▀░░░▀░▀░▀░▀
#

# ? WorkSpaces
bspc monitor -d 一 二 三 四 五 六 七 八
bspc monitor HDMI-A-0 -d 九 十

# ? Keybinding
sxhkd &

# ? Polybar
$HOME/.config/bspwm/polybar

# ? Extra
xsetroot -cursor_name left_ptr &
xset -dpms s off & # disable screen blanking
dunst &
bspc config split_ratio          0.50
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bsp-layout set tall -- --master-size 0.5 &

# ? Borders
$HOME/.config/bspwm/bspborders

# ? Autostart
$HOME/.config/bspwm/autostart

# ? Rules
$HOME/.config/bspwm/rules
