#!/bin/bash
COUNT_MONIOR=$(xrandr --query | grep " connected" | cut -d" " -f1 | wc -l)
echo "$COUNT_MONIOR"
if [[ "$COUNT_MONIOR" -eq 1 ]]; then
    bspc monitor -d 一 二 三 四 五 六 七 八 九 十
else
    bspc monitor -d 一 二 三 四 五 六 七 八
    bspc monitor HDMI-A-0 -d 九 十
fi
